name: flutter_advanced
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^1.1.6
  retrofit: ^3.3.1
  analyzer: ^5.2.0
  dio: ^4.0.6
  json_serializable: ^6.5.4
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.15
  freezed: ^2.3.0
  get_it: ^7.2.0
  lottie: ^2.0.0
  country_code_picker: ^2.0.2
  image_picker: ^0.8.6
  rxdart: ^0.27.7
  carousel_slider: ^4.2.0
  easy_localization: ^3.0.1
  flutter_phoenix: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.2


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true


  assets:
    - assets/images/splash_logo.png
    - assets/images/onboarding_logo1.svg
    - assets/images/onboarding_logo2.svg
    - assets/images/onboarding_logo3.svg
    - assets/images/onboarding_logo4.svg
    - assets/images/right_arrow_ic.svg
    - assets/images/left_arrow_ic.svg
    - assets/images/photo-camera.svg
    - assets/images/change_lang_ic.svg
    - assets/images/contact_us_ic.svg
    - assets/images/invite_friends_ic.svg
    - assets/images/logout_ic.svg
    - assets/images/right_arrow_settings_ic.svg
    - assets/json/loading.json
    - assets/json/empty.json
    - assets/json/error.json
    - assets/json/success.json
    - assets/translations/ar-SA.json
    - assets/translations/en-US.json




  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300

